version: "3.9"

services:
  postgres:
    image: postgres:latest

    volumes:
      - postgres-data:/var/lib/postgresql/data
      
    env_file:
      - "./backend/.env"
    ports:
      - "5432:5432"
  backend:
    build:
      context: "./backend/"
      dockerfile: "Dockerfile"
    command: "make run"
    restart: always
    env_file:
      - "./backend/.env"
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    


volumes:
  postgres-data:
