"""embeddings

Revision ID: 008
Revises: 007
Create Date: 2023-12-17 13:04:02.572373

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: Optional[str] = '007'
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession_embeddingss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embeddings', postgresql.ARRAY(sa.NUMERIC(precision=53, asdecimal=False)), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['professions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession_embeddingss')
    # ### end Alembic commands ###
