"""Real_values

Revision ID: 011
Revises: 010
Create Date: 2023-12-17 14:01:37.914903

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "011"
down_revision: Optional[str] = "010"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profession_embeddings",
        "embeddings",
        existing_type=postgresql.ARRAY(sa.NUMERIC(precision=53, scale=0)),
        type_=postgresql.ARRAY(sa.REAL()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profession_embeddings",
        "embeddings",
        existing_type=postgresql.ARRAY(sa.REAL()),
        type_=postgresql.ARRAY(sa.NUMERIC(precision=53, scale=0)),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
