"""group_embeddings

Revision ID: 012
Revises: 011
Create Date: 2023-12-17 14:06:20.993612

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "012"
down_revision: Optional[str] = "011"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_group_embedings", sa.Column("embeddings", postgresql.ARRAY(sa.REAL()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_group_embedings", "embeddings")
    # ### end Alembic commands ###
