"""group_pk

Revision ID: 013
Revises: 012
Create Date: 2023-12-17 14:10:23.563710

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "013"
down_revision: Optional[str] = "012"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "vk_group_embedings", "vk_groups", ["id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vk_group_embedings", type_="foreignkey")
    # ### end Alembic commands ###
