"""embeddings

Revision ID: 015
Revises: 014
Create Date: 2023-12-17 14:18:25.517267

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "015"
down_revision: Optional[str] = "014"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_groups", sa.Column("embeddings", postgresql.ARRAY(sa.REAL()), nullable=False)
    )
    op.drop_column("vk_groups", "eembeddings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_groups",
        sa.Column("eembeddings", postgresql.ARRAY(sa.REAL()), autoincrement=False, nullable=False),
    )
    op.drop_column("vk_groups", "embeddings")
    # ### end Alembic commands ###
