"""external_courses

Revision ID: 017
Revises: 016
Create Date: 2023-12-17 18:33:09.986039

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "017"
down_revision: Optional[str] = "016"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profession_course_association",
        sa.Column("profession_id", sa.Integer(), nullable=True),
        sa.Column("external_course_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_course_id"],
            ["external_courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
        ),
    )
    op.add_column("external_courses", sa.Column("portfolio_text", sa.Text(), nullable=True))
    op.add_column("external_courses", sa.Column("profession_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "external_courses", "professions", ["profession_id"], ["id"])
    op.drop_column("external_courses", "portfolioText")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_courses",
        sa.Column("portfolioText", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "external_courses", type_="foreignkey")
    op.drop_column("external_courses", "profession_id")
    op.drop_column("external_courses", "portfolio_text")
    op.drop_table("profession_course_association")
    # ### end Alembic commands ###
