"""profession_id_in_course

Revision ID: 018
Revises: 017
Create Date: 2023-12-17 19:43:40.124408

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "018"
down_revision: Optional[str] = "017"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "external_courses_profession_id_fkey", "external_courses", type_="foreignkey"
    )
    op.drop_column("external_courses", "profession_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_courses",
        sa.Column("profession_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "external_courses_profession_id_fkey",
        "external_courses",
        "professions",
        ["profession_id"],
        ["id"],
    )
    # ### end Alembic commands ###
