"""ExternalCourse_source_fix

Revision ID: 019
Revises: 018
Create Date: 2023-12-17 20:34:42.857073

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "019"
down_revision: Optional[str] = "018"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_courses", sa.Column("source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_courses", "source")
    # ### end Alembic commands ###
