"""fk_fix

Revision ID: 022
Revises: 021
Create Date: 2023-12-18 00:00:35.256390

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "022"
down_revision: Optional[str] = "021"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "profession_recomendations_profession_id_fkey",
        "profession_recomendations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "profession_recomendations", "professions", ["profession_id"], ["id"]
    )
    op.drop_constraint(
        "profession_visits_profession_id_fkey", "profession_visits", type_="foreignkey"
    )
    op.create_foreign_key(None, "profession_visits", "professions", ["profession_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profession_visits", type_="foreignkey")
    op.create_foreign_key(
        "profession_visits_profession_id_fkey",
        "profession_visits",
        "vk_users",
        ["profession_id"],
        ["id"],
    )
    op.drop_constraint(None, "profession_recomendations", type_="foreignkey")
    op.create_foreign_key(
        "profession_recomendations_profession_id_fkey",
        "profession_recomendations",
        "vk_users",
        ["profession_id"],
        ["id"],
    )
    # ### end Alembic commands ###
